/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    framedflatplate: THREE.Mesh
  }
  materials: {
    ['sargadelos.a.001']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/plate.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['sargadelos.a.001']}
        geometry={nodes.framedflatplate.geometry}
        rotation={[0, 1.57, 0]}
      />
    </group>
  )
}

useGLTF.preload('/plate.glb')
